language: node_js
node_js:
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- '6.0'
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: ccTzkZGbrgJs0IAAtlZ0WjhM5wdW4sAXA5dL17iOboQyNheuu23y9Dgmd1OwMYxDHsMSXk33nOaXeA+rSPg7QKwyTcNEfKOJmvdSIbZeFtRjawAMgdZFRrhOB0k0Nqdk87iDzOcNXk6o0V0FlAc7LR8SSFUhkDOreOMbXkdwTYZkVBs/Y/GGJBUa/MwKnYD8H4d0AULOy1NFc1IRqQg2UkBEFWvDB0uFFwpAZcM+cS74+c3VlzrNLGfwLLTEt+dW7XnjsTs10CvLKT1VixgnqZi5D+Y2BOjKO0YJaNG3Xb5KupPBT5fsMKDxIk9a82YD96tsVm36LrN+wNP3vvuanQY3An4yWNqWXZ/uz9XpMxtoQhbaApdwJkG5niMHuKI77ya7LG1w27wDzdieP91P/mdZTQ5lExoBnvtuUa4E5xUSXAPmN9z2QFgkjz1w+aa0SHmepCmzKOiKNmFSjrJgwkttbjqJae5Y/IOn1ngKOwcaUo0jsD0Pn6HXD/Ow6neRC0v0DBS6+i+y5zxyKIpppNj0xmth0xFWny3osR8SissWXVCEh1H1k9ufcGAHDXppNh+5kAze/dCKdVrdniJ9mg229X/fNoAeBlbztHlWqsRuN57bXugI4mYecG77zUGnTkelU9TEWZ8f80rZPB95SyM6tzM8NSzgp1WBO2HbkR8=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: ksLoQGm0zwXg/giTCPpGfEOn9wT7AGgGJr4CUt+6OCo3+GdNOTcvi47cmNMGLhhiKP4rS0VPquZQ1pNVjXzmKjq+6Mg6BWqMpUQMsHAwHGrVCxaGMW3YdkUOhgMkeEmcl2ckJdsH5NtYv5pfpn78FgD6dqP4gy1DGLk4fmWq1BK11jAYFDMtWqnV2sX5fCbG6shRLeRQH2BWGVXUt8/5LFEtQkWItNDt8KYw685jur44Y10nrT67e3YTrMeQlxHYH3yjN9qg1s8s1SGs35bWIfB7dR+mpwTkf1P6f7VaA1zXpYu9eQys2yhHObm31wwSLBgMML5PTftbP5+y3bVMXafYLddAVJevweVBafXkmPmIK+mVuz5KdvcPuGOIc59lkV9qCC+vo9eAilo8z1YjHsdMe1gBYZEf339BSZd+eEsHF6D6ArQl3FzafGB588p1oX0BeVnb2Qi+eDJsuENUTfBZingPWD9OOj+VzFPzB9G/MqVn/eafZQ+fDtTWER9vDOsuosVxFKvf3QxCNdnAVm4ZhGyuGdhvHyIq5YYDPbMW4UViO6e7pVbIFMP9yci+dW2kVv8vHLaaWyL64LxOQ28CIo7MTayk2nWdEXKEiZ0zv1eHPV/Tf5bbVrLCsevNzj2zyMlStswQ4X8adv+d5y6ypGLPCI68gi94gZWcDEc=
    file:
      - "collapse-white-space.js"
      - "collapse-white-space.min.js"
    on:
      tags: true
      node: '6.0'
